In [2]:
print("Hello World!")
print("i'm just a beginner")

Hello World!
i'm just a beginner


In [2]:
import numpy as np

In [10]:
a=np.array([1,2,3])
print(a)
b=np.array([[3,4,5],[1,2,3]])
print(b)
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[1 2 3]
[[3 4 5]
 [1 2 3]]


In [8]:
print(b.ndim)
print(b.shape)

2
(2, 3)


In [26]:
print(b[1,0:3:2])

a[0]=9
print(a)

[1 3]
[9 2 3]


In [34]:
c=np.repeat(b,3,axis=0)
print(c)

[[3 4 5]
 [3 4 5]
 [3 4 5]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
